### ISSUE TITLE
`use_bioc*` functions for usethis

### ISSUE THREAD

**Issue by jimhester** [lshep/MakeAPackage#1]
Would it be useful to have some `use_bioc_` helpers in [usethis](https://github.com/r-lib/usethis)?

`use_bioc_travis()` could create a `.travis.yml` file with something like

```yaml
language: r
r:
  - bioc-release
  - bioc-devel

sudo: false
cache: packages

bioc_packages:
  - BiocCheck

before_script:
  - R CMD BiocCheck .
```

Which would automatically run the package on bioc-release devel on travis and run BiocCheck before R CMD check.

A `use_bioc_vignette()` which would use `BiocStyle::html_document()`.

A `use_bioc_package()` would create a package with `BiocViews` in the DESCRIPTION (and potentially suggest categories?)

If any of the above ideas sound useful to the Bioconductor community I would encourage you to think about submitting a PR for them.
